AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for Terraform AI Agent - Allows secure resource creation in your AWS account'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Terraform AI Configuration'
        Parameters:
          - TerraformAIAccountId
          - ExternalId
    ParameterLabels:
      TerraformAIAccountId:
        default: 'Terraform AI AWS Account ID'
      ExternalId:
        default: 'Your Unique External ID'

Parameters:
  TerraformAIAccountId:
    Type: String
    Default: '639713290923'
    Description: 'The AWS account ID where Terraform AI backend runs (provided by Terraform AI)'
    AllowedPattern: '^[0-9]{12}$'
    ConstraintDescription: 'Must be a valid 12-digit AWS account ID'
  
  ExternalId:
    Type: String
    Description: 'Unique External ID for security (prevents confused deputy attack)'
    MinLength: 16
    MaxLength: 1224
    AllowedPattern: '^[a-zA-Z0-9+=,.@:\/-]*$'
    ConstraintDescription: 'Must be 16-1224 characters'

Resources:
  TerraformAIExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TerraformAI-ExecutionRole
      Description: 'Allows Terraform AI to create and manage AWS resources securely'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowTerraformAIAssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${TerraformAIAccountId}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: TerraformAI-ResourceManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: S3FullAccess
                Effect: Allow
                Action:
                  - 's3:CreateBucket'
                  - 's3:DeleteBucket'
                  - 's3:GetBucket*'
                  - 's3:ListBucket*'
                  - 's3:PutBucket*'
                  - 's3:GetObject*'
                  - 's3:PutObject*'
                  - 's3:DeleteObject*'
                  - 's3:ListAllMyBuckets'
                Resource: '*'
              
              - Sid: EC2Management
                Effect: Allow
                Action:
                  - 'ec2:Describe*'
                  - 'ec2:RunInstances'
                  - 'ec2:TerminateInstances'
                  - 'ec2:StartInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:AuthorizeSecurityGroupIngress'
                  - 'ec2:AuthorizeSecurityGroupEgress'
                  - 'ec2:RevokeSecurityGroupIngress'
                  - 'ec2:RevokeSecurityGroupEgress'
                  - 'ec2:CreateKeyPair'
                  - 'ec2:DeleteKeyPair'
                Resource: '*'
              
              - Sid: LambdaManagement
                Effect: Allow
                Action:
                  - 'lambda:CreateFunction'
                  - 'lambda:DeleteFunction'
                  - 'lambda:GetFunction'
                  - 'lambda:ListFunctions'
                  - 'lambda:UpdateFunctionCode'
                  - 'lambda:UpdateFunctionConfiguration'
                  - 'lambda:InvokeFunction'
                  - 'lambda:AddPermission'
                  - 'lambda:RemovePermission'
                  - 'lambda:TagResource'
                  - 'lambda:UntagResource'
                Resource: '*'
              
              - Sid: DynamoDBManagement
                Effect: Allow
                Action:
                  - 'dynamodb:CreateTable'
                  - 'dynamodb:DeleteTable'
                  - 'dynamodb:DescribeTable'
                  - 'dynamodb:ListTables'
                  - 'dynamodb:UpdateTable'
                  - 'dynamodb:TagResource'
                  - 'dynamodb:UntagResource'
                Resource: '*'
              
              - Sid: RDSManagement
                Effect: Allow
                Action:
                  - 'rds:CreateDBInstance'
                  - 'rds:DeleteDBInstance'
                  - 'rds:DescribeDBInstances'
                  - 'rds:ModifyDBInstance'
                  - 'rds:ListTagsForResource'
                  - 'rds:AddTagsToResource'
                  - 'rds:RemoveTagsFromResource'
                Resource: '*'
              
              - Sid: CloudWatchLogs
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DeleteLogGroup'
                  - 'logs:DeleteLogStream'
                Resource: '*'
              
              - Sid: IAMLimitedAccess
                Effect: Allow
                Action:
                  - 'iam:GetRole'
                  - 'iam:PassRole'
                  - 'iam:CreateRole'
                  - 'iam:DeleteRole'
                  - 'iam:AttachRolePolicy'
                  - 'iam:DetachRolePolicy'
                  - 'iam:PutRolePolicy'
                  - 'iam:DeleteRolePolicy'
                  - 'iam:GetRolePolicy'
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/TerraformAI-*'
              
              - Sid: VPCManagement
                Effect: Allow
                Action:
                  - 'ec2:CreateVpc'
                  - 'ec2:DeleteVpc'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:ModifyVpcAttribute'
                  - 'ec2:CreateSubnet'
                  - 'ec2:DeleteSubnet'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:CreateInternetGateway'
                  - 'ec2:DeleteInternetGateway'
                  - 'ec2:AttachInternetGateway'
                  - 'ec2:DetachInternetGateway'
                  - 'ec2:CreateRouteTable'
                  - 'ec2:DeleteRouteTable'
                  - 'ec2:AssociateRouteTable'
                  - 'ec2:DisassociateRouteTable'
                  - 'ec2:CreateRoute'
                  - 'ec2:DeleteRoute'
                Resource: '*'
              
              - Sid: APIGatewayManagement
                Effect: Allow
                Action:
                  - 'apigateway:*'
                Resource: '*'
      Tags:
        - Key: Name
          Value: TerraformAI-ExecutionRole
        - Key: ManagedBy
          Value: TerraformAI
        - Key: Purpose
          Value: 'Secure infrastructure automation'

Outputs:
  RoleArn:
    Description: 'IAM Role ARN - Copy this and paste it into Terraform AI'
    Value: !GetAtt TerraformAIExecutionRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-RoleArn'
  
  RoleName:
    Description: 'IAM Role Name'
    Value: !Ref TerraformAIExecutionRole
    Export:
      Name: !Sub '${AWS::StackName}-RoleName'
  
  ExternalId:
    Description: 'External ID used for this role (keep this secret!)'
    Value: !Ref ExternalId
  
  AccountId:
    Description: 'Your AWS Account ID'
    Value: !Ref AWS::AccountId
  
  Instructions:
    Description: 'Next Steps'
    Value: 'Copy the RoleArn above and paste it into Terraform AI to complete the setup'